test: graph1 graph2 graph3

graph1:
	@echo 'Graph1 execution:'
	python3 longest-path.py -a 1000 -i 50 -k 10 input/datasets/graph1.txt

graph2:
	@echo 'Graph2 execution:'
	python3 longest-path.py -a 500 -i 50 -k 10 input/datasets/graph2.txt

graph3:
	@echo 'Graph3 execution:'
	python3 longest-path.py -a 3000 -i 50 -k 10 input/datasets/graph3.txt
