test: graph1 graph2 graph3

graph1:
	@echo 'Graph1 execution:'
	python3 longest-path.py input/datasets/graph1.txt

graph2:
	@echo 'Graph2 execution:'
	python3 longest-path.py input/datasets/graph2.txt

graph3:
	@echo 'Graph3 execution:'
	python3 longest-path.py input/datasets/graph3.txt
